Add swift-docc-plugin

diff --git a/.github/workflows/documentation.yml b/.github/workflows/documentation.yml
--- a/.github/workflows/documentation.yml
+++ b/.github/workflows/documentation.yml
@@ -19,9 +19,6 @@ jobs:
   build:
     runs-on: macos-13
     steps:
-#      - name: Select Xcode 14.3
-#        run: sudo xcode-select -s /Applications/Xcode_14.3.app
-
       - name: Checkout Package
         uses: actions/checkout@v3
         with:
@@ -51,24 +48,34 @@ jobs:
               git checkout .;
               git checkout "$tag";
               
+              CURRENT_DIR=$(pwd)
+              rm -rf "$CURRENT_DIR/generated_docs"
+              mkdir "$CURRENT_DIR/generated_docs"
+
+              xcodebuild clean -scheme LoggerLibrary -destination "generic/platform=iOS" -derivedDataPath "$CURRENT_DIR/generated_docs"
+              xcodebuild docbuild -scheme LoggerLibrary -destination "generic/platform=iOS" -derivedDataPath "$CURRENT_DIR/generated_docs"
+              if [ $? -ne 0 ]; then
+                  echo "Documentation generation failed."
+                  exit 1
+              fi
+              
+              # archive .doccarchive
+              DOCCARCHIVE_PATH="$CURRENT_DIR/generated_docs/Build/Products/Debug-iphoneos/"
+              DOCCARCHIVE_NAME='LoggerLibrary.doccarchive'
+              OUTPUT_DIR="$(pwd)/build"
+              cd $DOCCARCHIVE_PATH
+              cd $CURRENT_DIR
+              mkdir docs-out
+              mkdir docs-out/"$tag"
+
+
               swift package plugin generate-documentation \
                 --source-service github \
+                --output-path /Users/ondrejvesely/Xcode/LoggerLibrary/docs-out/"$tag" \
                 --target LoggerLibrary \
                 --hosting-base-path /loggerlibrary/"$tag" \
                 --source-service-base-url https://github.com/Ondra14/LoggerLibrary.git \
-                --checkout-path docs-out/"$tag"
-              
-  
-  
-#              swift package \
-#                --allow-writing-to-directory docs-out/"$tag" \
-#                generate-documentation \
-#                --target LoggerLibrary \
-#                --output-path docs-out/"$tag" \
-#                --transform-for-static-hosting \
-#                --hosting-base-path /loggerlibrary/"$tag" \
-#                && echo "✅ Documentation generated for LoggerLibrary @ "$tag" release." \
-#                || echo "⚠️ Documentation skipped for LoggerLibrary @ "$tag".";
+                --checkout-path /Users/ondrejvesely/Xcode/LoggerLibrary
             fi;
           done
 
